version: '3.2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=pgdb
    - POSTGRES_USER=pgsuser
    - POSTGRES_PASSWORD=pgspwd
    ports:
    - "5432:5432"

volumes:
  db-data: {}